#!/usr/bin/env sh
set -eu

hook_name="$(basename "$0")"
hook_script=".git/hooks/$hook_name"

[ -e "$hook_script" ] && $hook_script

gitleaksEnabled=$(git config --bool hooks.gitleaks)
cmd="gitleaks --verbose --redact --pretty"
if [ ${gitleaksEnabled} = "true" ]; then
    $cmd
    if [ $? -eq 1 ]; then
cat <<\EOF
Error: gitleaks has detected sensitive information in your changes.
If you know what you are doing you can disable this check using:
    git config hooks.gitleaks false
EOF
    exit 1
    fi
fi
