#!/usr/bin/env bash

set -e
exec 2> >(while read line; do echo -e "\e[01;31m$line\e[0m"; done)

MY_GPG_KEY_ID="BE9C8BCF2398599C"

script_name="$(basename "$0")"
dotfiles_dir="$(cd "$(dirname "$0")"; pwd)"
cd "$dotfiles_dir"

source ./lib/functions.sh
source ./lib/stages/setup_sources.sh
source ./lib/stages/setup_packages.sh
source ./lib/stages/setup_configs.sh

if [[ -v SETUP_HOST_TYPE ]]; then
  head "Working with host type ${SETUP_HOST_TYPE}"
  else
  if [[ -f ~/.hosttype ]]; then
    SETUP_HOST_TYPE=`cat ~/.hosttype`
  else
    SETUP_HOST_TYPE="unknown"
  fi
fi

if [[ "$(whoami)" != "root" ]]; then
  head "Setting up dotfiles for current user..."
  stage_setup_user_bin
  stage_setup_user_configs
  stage_setup_user_services

  if [[ "$SETUP_HOST_TYPE" =~ "desktop" ]]; then
    head "Setup git sources for current user..."
    #stage_setup_sources
  fi

  if ! gpg -k | grep "$MY_GPG_KEY_ID" > /dev/null; then
    head "Importing my public PGP key"
    curl -s https://keybase.io/bigforcegun/pgp_keys.asc | gpg --import
    gpg --trusted-key "$MY_GPG_KEY_ID" > /dev/null
  fi

  head "Switching to root user to continue..."
  sudo -s "$dotfiles_dir/$script_name"
fi

if [[ "$(whoami)" == "root" ]]; then
  head "Setting up /etc configs..."
  stage_setup_root_configs
  echo "Done"

  head "Setting up root services..."
  stage_setup_root_services
  echo "Done"

  head "Configuring firewall..."
  stage_setup_ufw_services
  echo "Done" 

  head "Setup base packgages..."
  #stage_install_base_packgages

  head "Setting dash as /usr/bin/sh..."
  ln -sfT dash /usr/bin/sh
  echo "Done"

  if [[ "$SETUP_HOST_TYPE" =~ "desktop" ]]; then

    #head "Adding PPAs..."
    #stage_add_ppas

    #head "Purging packages..."
    #stage_purge_packages

    #head "Install user packages..."
    #stage_install_user_packages

    #head "Install utils packages..."
    #stage_install_utils_packages

    #head "Install dev packages..."
    #stage_install_dev_packages

    #head "Install KDE packages..."
    #stage_install_kde_packages

    #head "Install remote packages..."
    #stage_install_remote_packages

    #head "Disable services..."
    #stage_disable_services

    #head "Install RVM..."
    #stage_rvm

    #head "Install RVM rubies..."
    #stage_rvm_rubies

    #head "Finalising..."
    stage_finalize_install
  fi
fi