#!/usr/bin/env bash

set -e
exec 2> >(while read line; do echo -e "\e[01;31m$line\e[0m"; done)

source ./lib/functions.sh

script_name="$(basename "$0")"
dotfiles_dir="$(
    cd "$(dirname "$0")"
    pwd
)"
cd "$dotfiles_dir"


PKG_CATEGORIES=(
    "developer"
    "hardware"
    # "plasma"
    "i3"
    "libs"
    "system"
    "themes"
    "utils_cli"
    "utils_user"
)

head "Purge packages..."

# pt purge irqbalance laptop-mode-tools -y

head "Install desktop packages..."


export DEBIAN_FRONTEND=noninteractive
for category in "${PKG_CATEGORIES[@]}"
do
    head " Installing packages from category ${category}"
    sudo apt install -y $(list_from_file packages/ubuntu/${category}.txt)
done
