#!/usr/bin/env bash

set -e
exec 2> >(while read line; do echo -e "\e[01;31m$line\e[0m"; done)

source ./lib/functions.sh

script_name="$(basename "$0")"
dotfiles_dir="$(
    cd "$(dirname "$0")"
    pwd
)"
cd "$dotfiles_dir"


head "Setup base packages..."
list_from_file packages/mac/init.txt | xargs brew install



head "Setup base packages..."
list_from_file packages/mac/dev.txt | xargs brew install
